name: Test
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🍔🍟🥤
        uses: actions/checkout@v3.0.2
        with:
          persist-credentials: false

      - name: Use Node.js 😂
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'

      - name: Test 🧪
        run: |
          npm ci
          npm run lint
          npm test
